# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('price', models.FloatField()),
                ('venue', models.CharField(default='', max_length=50)),
                ('food_type', models.CharField(choices=[('1', 'Breakfast'), ('2', 'Lunch'), ('3', 'Dinner')], max_length=1)),
            ],
            options={
                'verbose_name': 'Food',
            },
        ),
        migrations.CreateModel(
            name='PropertyRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('price', models.FloatField()),
                ('bathrooms', models.IntegerField()),
                ('area', models.FloatField()),
                ('rating', models.FloatField()),
                ('property_type', models.CharField(choices=[('1', 'Condo'), ('2', 'HDB')], max_length=1)),
                ('property_name', models.CharField(default='', max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Property Rental',
                'verbose_name_plural': 'Property Rentals',
            },
        ),
        migrations.CreateModel(
            name='PublicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
