# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaglife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrental',
            name='image_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='propertyrental',
            name='image_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='propertyrental',
            name='image_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='propertyrental',
            name='image_4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='propertyrental',
            name='image_5',
            field=models.CharField(default='', max_length=255),
        ),
    ]
